brainstorm/config/routes.rb
Rails.application.routes.draw do

  root to: 'users#index'

  post 'users/create' => 'users#create'

  post 'login' => 'users#login'

  get '/users/logout' => 'users#logout'

  get '/users/:id' => 'users#show', as: 'user_show'

  get 'games/leaderboard' => 'games#show'

  get 'games/play' => 'games#new'

  post 'games/create' => 'games#create'

  get 'users/edit'

  patch 'users/update'

  delete 'users/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

brainstorm/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

brainstorm/app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
end

brainstorm/app/models/user.rb
# require 'bcrypt'

class User < ApplicationRecord
  # include BCrypt

  has_many :games

  has_secure_password
  #
  # attr_accessor :email, :password, :password_confirmation
  #
  # validates_uniqueness_of :email
  #
  # def password
  #   @password ||= Password.new(password_hash)
  # end
  #
  # def password=(new_password)
  #   @password = Password.create(new_password)
  #   self.password_hash = @password
  # end
end

brainstorm/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  skip_before_filter :verify_authenticity_token

  def signed_in?
    unless session[:user_id] && User.find(session[:user_id])
      flash[:notice] = "Please log in to proceed."
      redirect_to root_path
    end
  end
end

brainstorm/app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :signed_in?, only: [:show]

  def new
    user_games = Game.where(user_id: session[:user_id])
    @personal_best = user_games.order(:score).last.score
    @high_score = Game.order(:score).last.score
    p @personal_best
  end

  def create
    @games = Game.all
    @game = Game.new(score: params[:score], user_id: session[:user_id])
    @game.save
    flash[:notice] = "Thanks for playing!"
    redirect_to user_show_path(:id => session[:user_id])
  end

  def show
    @top_five = Game.order(score: :desc).first(5)
  end


end

brainstorm/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in?, only: [:show]
  def index
    @user = User.new
  end

  # def new
  #   @user = User.new
  # end

  def create
    p params
    @user = User.new(name: params[:'player-name-reg'], email: params[:email])
    @user.password = params[:password]
    @user.password_confirmation = params[:password_confirmation]
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_show_path(:id => @user.id), notice: "Thank you for signing up!"
    else
      redirect_to root_path
    end
  end

  def login
    p User.find_by(name: params[:'player-name-login'])
    @user = User.find_by(name: params[:'player-name-login'])
    if @user && @user.authenticate(params[:'player-password-login'])
      p "SUCCESSFULZ"
      session[:user_id] = @user.id
      redirect_to user_show_path(:id => @user.id)
    else
      p "FAILSFULL"
      flash[:notice] = "Username or password is invalid."
      redirect_to root_path
    end
  end

  def show
    @user = User.find(session[:user_id])
    @personal_best = Game.where(user_id: session[:user_id]).max
    p @personal_best
  end

  def logout
    p "Tryin to log out!"
    session[:user_id] = nil
    flash[:notice] = "You have successfully logged out."
    redirect_to root_path
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

brainstorm/app/helpers/application_helper.rb
module ApplicationHelper
end

brainstorm/app/helpers/games_helper.rb
module GamesHelper
end

brainstorm/app/helpers/users_helper.rb
module UsersHelper
end

brainstorm/app/views/games/new.html.haml
!!! 5
%html.game
  %head
    %meta(charset='UTF-8')
    %meta(content='width=device-width, initial-scale=1' name='viewport')
    %title Brainstorm - Game
    %link(href="https://fonts.googleapis.com/css?family=Fredoka+One%7COpen+Sans" rel="stylesheet")
    %link(rel="icon" type='image/png' href="/assets/storm_logo.png")
    %link(rel='stylesheet' href='/assets/main.min.css')
  %body.game
    %audio.music(style="display: none" loop)
      %source.song(style="display:none" src="/assets/game_music.mp3" type="audio/mpeg")
    %header
      %img.storm(src='/assets/storm_logo.png' alt='grey storm logo')
      %img.lightning(src='/assets/storm_logo_white.png' alt='white storm logo')
      %h1.logo(data-shadow='brainstorm') brainsto.rm
      %nav.menu
        %ul.navbar
          %li.play
            %a.play(href='/games/play') Play
          %li.leaderboard
            %a.leaderboard(href='/games/leaderboard') Leaderboard
          %li.account
            %a.account(href="/users/#{session[:user_id]}") Account
          %li.logout
            %a.logout(href='/users/logout') Logout
      %nav.menu-small
        %h3.nav
          %a.menu Menu
        %div.drop-nav
          %ul
            %li.play
              %a.play(href='/games/play') Play
            %li.leaderboard
              %a.leaderboard(href='/games/leaderboard') Leaderboard
            %li.account
              %a.account(href="/users/#{session[:user_id]}") Account
            %li.logout
              %a.logout(href='/users/logout') Logout
    %input.mute-button(type="button" value="Mute")
    %input.start-game(type="button" value="Start Game")
    .game-container
      .scores-container
        %ul
          %li.solution-score +100
          %li.current-score SCORE: <br> 0
          %li.personal-best PERSONAL BEST: <br> #{@personal_best}
          %li.high-score HIGH SCORE: <br> #{@high_score}
      %img.cloudOne(src='/assets/clouds_3.png' alt='cloud image')
      %img.cloudTwo(src='/assets/clouds_4.png' alt='cloud image')
      %img.cloudThree(src='/assets/clouds_5.png' alt='cloud image')
      %img.cloudFour(src='/assets/clouds_6.png' alt='cloud image')
      %img.cloudFive(src='/assets/clouds_5.png' alt='cloud image')
      %img.cloudSix(src='/assets/clouds_4.png' alt='cloud image')
      %form.solution
        %input.solution-field(id="solution-field" type="text" placeholder="=" autocomplete='off')
      %form.score-submission(action="create" method="post")
        %input.score-to-send(type="text" name="score")
        -# %input.user-id(type="text" readonly="readonly" name="user-id")
        %input(id="submit" type="submit" value="SUBMIT")
      .grass-container
        %img.grass(src='/assets/grass.png')

    %script(src="/assets/vendor.min.js")
    %script(src="/assets/game.js")

brainstorm/app/views/games/show.html.haml
!!! 5
%html.leaderboard(lang='en')
  %head
    %meta(charset='UTF-8')
    %meta(content='width=device-width, initial-scale=1' name='viewport')
    %title brainsto.rm
    %link( href="https://fonts.googleapis.com/css?family=Fredoka+One|Open+Sans|Lato" rel="stylesheet")
    %link(rel="icon" type='image/png' href="/assets/storm_logo.png")
    %link(rel="stylesheet" href="/assets/main.min.css")
%body.leaderboard
  -# - user = [{user_name: 'Lindsey Adams', high_score: '12,000'}, {user_name: 'Jason Carr', high_score: '10,000'}, {user_name: 'Gabe Estes', high_score: '9,700'}, {user_name: 'Jenn Tustin', high_score: '9,300'}, {user_name: 'Dan Yuschick', high_score: '3,200'}]
  -# - topPlayer = {user_name: 'Somebody Else', high_score: '20,000'}
  %header
    %img.storm(src='/assets/storm_logo.png' alt='grey storm logo')
    %img.lightning(src='/assets/storm_logo_white.png' alt='white storm logo')
    %h1.logo(data-shadow='brainstorm') brainsto.rm
    %nav.menu
      %ul.navbar
        %li.play
          %a.play(href='/games/play') Play
        %li.leaderboard
          %a.leaderboard(href='/games/leaderboard') Leaderboard
        %li.account
          %a.account(href="/users/#{session[:user_id]}") Account
        %li.logout
          %a.logout(href='/users/logout') Logout
    %nav.menu-small
      %h3.nav
        %a.menu Menu
      %div.drop-nav
        %ul
          %li.play
            %a.play(href='/games/play') Play
          %li.leaderboard
            %a.leaderboard(href='/games/leaderboard') Leaderboard
          %li.account
            %a.account(href="/users/#{session[:user_id]}") Account
          %li.logout
            %a.logout(href='/users/logout') Logout
  %section.leaderboard-container
    %div.header
      %img.award(src='/assets/award_icon.svg' alt='award icon')
      %h3 Top Players
    %div.stats
      %ul.players
        - @top_five.each do |user, index|
          %li.player{:class => '#{index}'}
            %p.rank(data-id='rank')
            %p.player-name(data-id='user-name')= user.user.name
            %p.score(data-id='high-score')
              %span= user.score

%script(src='/assets/vendor.min.js')
%script(src='/assets/leaderboard.js')

brainstorm/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Brainstorm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

brainstorm/app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

brainstorm/app/views/users/index.html.haml
!!! 5
%html.index(lang="en")
  %head
    %meta(charset='UTF-8')
    %meta(content='width=device-width, initial-scale=1' name='viewport')
    %title Brainstorm - LogIn
    %link( href="https://fonts.googleapis.com/css?family=Fredoka+One|Open+Sans" rel="stylesheet")
    %link(rel="icon" type='image/png' href="/assets/storm_logo.png")
    %link(rel='stylesheet' href='/assets/main.min.css')
  %body.index
    %header
      %img.storm(src='/assets/storm_logo.png' alt='grey storm logo')
      %img.lightning(src='/assets/storm_logo_white.png' alt='white storm logo')
      %h1.logo(data-shadow='brainstorm') brainsto.rm
    .index-container
      %h4
        - flash.each do |key, value|
          .alert{ :class => "alert-#{key}" }
          -# %button.close{ :data => { :dismiss => "alert" } } x
          %strong
            = value
      .new-or-returning
        %form
          %p
            %label(for="player-name-reg") Please Register or Login:
            %input(id="register" type="button" value="REGISTER")
            %input(id="login" type="button" value="LOGIN")
      .register
        -# %form(action="users/create" method="post")
        = form_for @user, url: users_create_path, method: :post do |f|
          - if @user.errors.any?
            %h2(class="error_messages") Form is invalid
            %ul
              - @user.errors.full_messages.each do |message|
                %li= message
          %p
            %label(for="player-name-reg") Player Name
            = f.text_field :name, class: "text-input", id:"player-name-reg", name:"player-name-reg", type:"text"
            %input(class="text-input" id="player-name-reg" name="player-name-reg" type="text")
            %span.requirement-right Player name must have at least 5 characters
          %p
            %label(for="email") Player Email
            %span.requirement-left Invalid email address
            = f.text_field :email, class: "text-input", id:"email", name:"email", type:"email"
            -# %input(class="text-input" id="email" name="email" type="email")
            %span.requirement-right Keep going
          %p
            %label(for="password") Password
            %span.requirement-left Enter a password with at least one capital letter (A-Z), one lowercase letter (a-z) and one number (0-9).
            = f.password_field :password, class:"text-input", id:"password", name:"password", type:"password"
            -# %input(class="text-input" id="password" name="password" type="password")
            %span.requirement-right Enter a password longer than 6 characters
          %p
            %label(for="confirm-password") Confirm Password
            = f.password_field :password_confirmation, class:"text-input", id:"confirm-password", name:"confirm-password", type:"password"
            -# %input(class="text-input" id="confirm-password" name="confirm-password" type="password")
            %span.requirement-left Please confirm your password
          %p
            = f.submit :post, id:"submit-register", type:"submit", value:"REGISTER"
            -# %input(id="submit-register" type="submit" value="REGISTER")
      .login
        %form(action="login" method="post")
          %p
            %label(for="player-name-login") Player Name
            -# = f.text_field :name, id:"password", name:"password", type:"password"
            %input(id="player-name-login" name="player-name-login" type="text")
            %span.requirement-right Enter your player name
          %p
          %p
            %label(for="player-password-login") Password
            %input(id="player-password-login" name="player-password-login" type="password")
            %span.requirement-right Enter your password
          %p
            %input(id="submit-login" type="submit" value="LOGIN")
    %script(src="/assets/vendor.min.js")
    %script(src="/assets/index.js")

brainstorm/app/views/users/show.html.haml
!!! 5
%html.profile(lang='en')
  %head
    %meta(charset='UTF-8')
    %meta(content='width=device-width, initial-scale=1' name='viewport')
    %title brainsto.rm
    %link( href="https://fonts.googleapis.com/css?family=Fredoka+One|Open+Sans|Lato" rel="stylesheet")
    %link(rel="icon" type='image/png' href="/assets/storm_logo.png")
    %link(rel="stylesheet" href="/assets/main.min.css")
%body.profile
  - user = {user_name: 'Lindsey Adams', high_score: '12,000', email:'linzma87@gmail.com', twitter:'@turmerictotebag', instagram:'@lindsmadams'}
  - topPlayer = {user_name: 'Somebody Else', high_score: '20,000'}
  %header
    %img.storm(src='/assets/storm_logo.png' alt='grey storm logo')
    %img.lightning(src='/assets/storm_logo_white.png' alt='white storm logo')
    %h1.logo(data-shadow='brainstorm') brainsto.rm
    %nav.menu
      %ul.navbar
        %li.play
          %a.play(href='/games/play') Play
        %li.leaderboard
          %a.leaderboard(href='/games/leaderboard') Leaderboard
        %li.account
          %a.account(href="/users/#{session[:user_id]}") Account
        %li.logout
          %a.logout(href='/users/logout') Logout
    %nav.menu-small
      %h3.nav
        %a.menu Menu
      %div.drop-nav
        %ul
          %li.play
            %a.play(href='/games/play') Play
          %li.leaderboard
            %a.leaderboard(href='/games/leaderboard') Leaderboard
          %li.account
            %a.account(href="/users/#{session[:user_id]}") Account
          %li.logout
            %a.logout(href='/users/logout') Logout
  %section.profile-container
    %div.initials
      %h3= @user.name[0].capitalize
    %ul.user-info
      %li.name(data-id='user-name')= @user.name
      %li.score(data-id='high-score')
        high score:
        %span= @personal_best.score
      %hr
      %li(data-id='twitter')
        %img(src='/assets/twitter_icon.png' alt='twitter icon')
        %p= @user.twitter
      %li.instagram(data-id='instagram')
        %img(src='/assets/instagram_icon.png' alt='instagram icon')
        %p= @user.instagram
      %li(data-id='email')
        %img(src='/assets/email_icon.png' alt='email icon')
        %p= @user.email
      %div.edit
        %img.edit(src='/assets/edit_icon.png' alt='edit icon')
    %ul.edit-info
      %li.name(data-id='user-name') #{user[:user_name]}
      %li.score(data-id='high-score')
        high score:
        %span= @personal_best.score
      %hr
      %form
        %li(data-id='twitter')
          %img(src='/assets/twitter_icon.png' alt='twitter icon')
          %input(placeholder='\@twitteraccount')
        %li.instagram(data-id='instagram')
          %img(src='/assets/instagram_icon.png' alt='instagram icon')
          %input(placeholder='Instagram')
        %li(data-id='email')
          %img(src='/assets/email_icon.png' alt='email icon')
          %input(placeholder='me\@you.com')
      %div.save
        %img.save(src='/assets/save_icon.png' alt='save icon')

  %script(src='/assets/vendor.min.js')
  %script(src='/assets/profile.js')